// Session
export const CREATE_SESSION = "CREATE_SESSION";
export const VALDIATE_SESSION = "VALDIATE_SESSION";
export const INVALIDATE_SESSION = "INVALIDATE_SESSION";
export const CLOSE_SESSION = "CLOSE_SESSION";

// Elements
export const SCAN = "SCAN";
export const SET_CURRENT_ELEMENT = "SET_CURRENT_ELEMENT";
export const SPY_ELEMENT = "SPY_ELEMENT";
export const FILTER_ELEMENTS = "FILTER_ELEMENTS";
export const SELECT_ELEMENT = "SELECT_ELEMENT";
export const DESELECT_ELEMENT = "DESELECT_ELEMENT";

// Other
export const SET_LOADING = "SET_LOADING";
export const INSPECTOR_ERROR = "INSPECTOR_ERROR";

// Layout
export const RESIZE_LAYOUT = "RESIZE_LAYOUT";
